steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c','docker build -f trainer.dockerfile . -t gcr.io/dtumlops-detr/testing']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dtumlops-detr/testing']

timeout: 3600s


